#DEV/BUILDER
FROM node:16 as builder

WORKDIR /usr/src/app

COPY ./node/* .

RUN npm install

#PROD
FROM node:16-alpine as prod

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

CMD [ "node", "index.js" ]